Add writing job outputs to a file in JSON format

diff --git a/sample-files/job.yaml b/sample-files/job.yaml
--- a/sample-files/job.yaml
+++ b/sample-files/job.yaml
@@ -1,39 +1,19 @@
 name: Test
-description: A simple workflow that would run simple bash steps
+description: Workflow with bash script steps
+outputs:
+  output_1:
+    value: '{{ .StepOutputs.step_1.output_1 }}'
+  output_2:
+    value: '{{ .StepOutputs.step_1.output_2 }}'
 steps:
-  - type: shellScript
+  - type: shell
     name: Step 1
+    id: step_1
     description: Simple test step
     continue_on_error: false
     script: |
-      echo ">>> STEP1: Standard Output Message";
-      >&2 echo ">>> STEP1: Standard Error Message";
-
-  - type: shellScript
-    name: Step 2
-    description: Simple test step 2
-    continue_on_error: true
-    script: |
-      echo "STEP2: I can count!";
-      
-      for i in 1 2 3 4 5; do
-        echo "STEP2: $i";
-        sleep 2;
-      done
-      
-      echo "Hello there!";
-      
-      cat >> /tmp/my-tmp-file <<EOF
-      Oh, just testing the heredoc
-      EOF
-      
-      echo "STEP2: Actually, I wanted to test multiple line bash script"
-      exit 124;
-
-  - type: shellScript
-    name: Step 3
-    description: Simple test step
-    continue_on_error: false
-    script: |
-      echo "STEP3: Let's cat the file:";
-      cat /tmp/my-tmp-file  
+      echo "Step1 Standard Output Message";
+      >&2 echo "Step1 Standard Error Message";
+      echo -n "output1" > $OUTPUTS_DIR/output_1
+      echo -n "output2" > $OUTPUTS_DIR/output_2
+      exit 4;
